### ISSUE TITLE
How do I create a video file from the output files?

### ISSUE THREAD

**Issue by fazil47** [facebookresearch/one_shot_3d_photography#3]
Videos like those showcased in the [project page](https://facebookresearch.github.io/one_shot_3d_photography/).

**Comment by jkopf** [comment]
Hey @fazil47 , I should clarify this better in the README. We're only open sourcing the depth network at this point. You can create 3D photos with the Facebook app, or, if you're looking for an OSS implementation, you could look at this code https://github.com/vt-vl-lab/3d-photo-inpainting
