### ISSUE TITLE
Output file shape

### ISSUE THREAD

**Issue by Nerdyvedi** [facebookresearch/one_shot_3d_photography#4]
Hi,
I was trying to create the video file using the numpy output.
But, the shape of the output list is [1,384,288,1]

I am not able to understand why it contains only a single one channel image. 

Would be really grateful if you could help. Thanks

**Comment by ak9250** [comment]
also interested in this

**Comment by jkopf** [comment]
Hey @Nerdyvedi, @ak9250, I should clarify this better in the README. We're only open sourcing the depth network at this point. You can create 3D photos with the Facebook app, or, if you're looking for an OSS implementation, you could look at this code https://github.com/vt-vl-lab/3d-photo-inpainting
